require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ExercisesController do

  def mock_exercise(stubs={})
    @mock_exercise ||= mock_model(Exercise, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all exercises as @exercises" do
      Exercise.stub(:all) { [mock_exercise] }
      get :index
      assigns(:exercises).should eq([mock_exercise])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise as @exercise" do
      Exercise.stub(:find).with("37") { mock_exercise }
      get :show, :id => "37"
      assigns(:exercise).should be(mock_exercise)
    end
  end

  describe "GET new" do
    it "assigns a new exercise as @exercise" do
      Exercise.stub(:new) { mock_exercise }
      get :new
      assigns(:exercise).should be(mock_exercise)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise as @exercise" do
      Exercise.stub(:find).with("37") { mock_exercise }
      get :edit, :id => "37"
      assigns(:exercise).should be(mock_exercise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created exercise as @exercise" do
        Exercise.stub(:new).with({'these' => 'params'}) { mock_exercise(:save => true) }
        post :create, :exercise => {'these' => 'params'}
        assigns(:exercise).should be(mock_exercise)
      end

      it "redirects to the created exercise" do
        Exercise.stub(:new) { mock_exercise(:save => true) }
        post :create, :exercise => {}
        response.should redirect_to(exercise_url(mock_exercise))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise as @exercise" do
        Exercise.stub(:new).with({'these' => 'params'}) { mock_exercise(:save => false) }
        post :create, :exercise => {'these' => 'params'}
        assigns(:exercise).should be(mock_exercise)
      end

      it "re-renders the 'new' template" do
        Exercise.stub(:new) { mock_exercise(:save => false) }
        post :create, :exercise => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise" do
        Exercise.stub(:find).with("37") { mock_exercise }
        mock_exercise.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :exercise => {'these' => 'params'}
      end

      it "assigns the requested exercise as @exercise" do
        Exercise.stub(:find) { mock_exercise(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:exercise).should be(mock_exercise)
      end

      it "redirects to the exercise" do
        Exercise.stub(:find) { mock_exercise(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(exercise_url(mock_exercise))
      end
    end

    describe "with invalid params" do
      it "assigns the exercise as @exercise" do
        Exercise.stub(:find) { mock_exercise(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:exercise).should be(mock_exercise)
      end

      it "re-renders the 'edit' template" do
        Exercise.stub(:find) { mock_exercise(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise" do
      Exercise.stub(:find).with("37") { mock_exercise }
      mock_exercise.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the exercises list" do
      Exercise.stub(:find) { mock_exercise }
      delete :destroy, :id => "1"
      response.should redirect_to(exercises_url)
    end
  end

end
